# Generated by Django 5.0.2 on 2024-02-22 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='users',
            name='DateTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 22, 16, 44, 18, 642273, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='district',
            field=models.CharField(default=datetime.datetime(2024, 2, 22, 16, 45, 17, 428771, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(default=datetime.datetime(2024, 2, 22, 16, 45, 26, 103804, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='blood_group',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
