# Generated by Django 5.0.2 on 2024-02-27 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_stock_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='weight',
            field=models.FloatField(default=0.0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='age',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='stock',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='stock',
            name='district',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pin',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='stock',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
