# Generated by Django 5.0.2 on 2024-02-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_stock_weight_alter_stock_age_alter_stock_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
